[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Nexus-e - DistIv"
authors = [{name = "Xuejiao Han", email = "xuhan@eeh.ee.ethz.ch"}]
dynamic = ["version", "description"]
